# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'credit_card_validator'
require 'credit_card_validator/payment_method'
require 'credit_card_validator/payment_method/credit_card'
require 'credit_card_validator/payment_method/amex'
require 'credit_card_validator/payment_method/discover'
require 'credit_card_validator/payment_method/master_card'
require 'credit_card_validator/payment_method/visa'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
